### ISSUE TITLE
In all your examples you use `l.id` - What is `l.id`?

### ISSUE THREAD

**Issue by Krutonium** [Digus/StardewValleyMods#104]
For example,
```
                MailDao.SaveLetter(
                    new Letter(
                        "LetterUniqueId"
                        ,"Letter custom text."
                        ,new List<Item> { new StardewValley.Object(60,5) }
                        ,(l)=>!Game1.player.mailReceived.Contains(l.Id)
                        ,Game1.player.mailReceived.Add(l.Id)
                    )                                  ^^^^
                );
```
It can't be the `l` declared directly above it - there's no way to access that.

![Example](https://user-images.githubusercontent.com/3945538/103599510-49505700-4ed3-11eb-9c9f-6f4a46de161b.PNG)

**Comment by Digus** [comment]
Yeah, that example is missing (l)=> in front of "Game1.player.mailReceived.Add(l.Id)"
Both are functions, one if the condition function and the other is the callback function.

**Comment by Krutonium** [comment]
Doi, I can't believe I didn't figure that out.
