### ISSUE TITLE
Clarify or revise SubtractTimeOfDay field

### ISSUE THREAD

**Issue by kdau** [Digus/StardewValleyMods#83]
The `SubtractTimeOfDay` field currently causes `Game1.timeOfDay`, which is in a clock face format like `1030` or `2345` where each hour is 100, to be subtracted from `MinutesUntilReady`, which is a number of minutes where each hour is 60. [This is the code location.](https://github.com/Digus/StardewValleyMods/blob/master/ProducerFrameworkMod/ProducerRuleController.cs#L109)

After a question from someone on Discord, I realized that this makes it difficult to use the field. For every additional hour that has passed in the world before the machine is started, another 40 minutes of difference accumulates between the two values being subtracted. If this is intentional, could you clarify the documentation to reflect that? If not, could you offer an alternate field or change the behavior of this field to subtract the total number of minutes that have passed in the day so far (i.e., `(Game1.timeOfDay / 100 - 6) * 60 + Game1.timeOfDay % 100`)?

**Comment by Digus** [comment]
That code was definitely buggy.
I will fix it in the next update.

**Comment by Digus** [comment]
It was implemented on version 1.4.2
